yegor256/rultor

- pom.xml
added an enforcer rule requiring java of version no less than 1.7
> #701 build failed under OS X

- src/main/java/com/rultor/agents/github/qtn/QnReferredTo.java
- src/main/resources/phrases_en_US.properties
- src/test/java/com/rultor/agents/github/qtn/QnReferredToTest.java
#683. QnReferredTo can answer if rultor is mentions in comment.
> #683. QnReferredTo can answer if rultor is mentions in comment.

- src/test/java/com/rultor/profiles/GithubProfileValidationTest.java
Implement validation tests based on 2014-07-13-basics.md file
> 698:  Implement validation tests based on 2014-07-13-basics.md file

- pom.xml
Resolve build problems with locale is not en_US
> 707: Resolve build problems with locale is not en_US

- src/test/java/com/rultor/agents/github/IndexesRequestsTest.java
- src/test/java/com/rultor/profiles/GithubProfileValidationTest.java
> Remove @todo puzzle from source code - Issue #681

- src/jekyll/_posts/2014/jul/2014-07-13-reference.md
#692 Documented that commands are optional in .rultor.yml
> #692 Documented that commands are optional in .rultor.yml

- src/main/resources/com/rultor/spi/talk.xsd
This PR contain the documentation of talk.xsd
> 742: Add documentation to talk.xsd

- pom.xml
- src/main/resources/com/rultor/spi/talk.xsd
> Fix qulice License.txt problems on Windows - Issue #752

- pom.xml
- src/main/java/com/rultor/agents/IndexesRequests.java
- src/main/java/com/rultor/spi/Talks.java
- src/test/java/com/rultor/agents/IndexesRequestsTest.java
Issue: https://github.com/yegor256/rultor/issues/733
> Fix of IndexesRequestsTest#retrievesIndexFromSibling failure

- years.sh
Just an obvious thing we missed :)
> exclude .idea fodler from years.sh checks

- pom.xml
Trivial issue made it through CR unnoticed, just the formatting throwing pdd off here :)
> fixed wrong format on puzzle

- src/docker-it/clear_docker_sshd.sh
- src/docker-it/run_docker_sshd.sh
Just some polishing to make the next step easier for performers.
> Sshd docker Fixes

- src/main/java/com/rultor/agents/Agents.java
- src/main/java/com/rultor/agents/daemons/EndsDaemon.java
- src/main/java/com/rultor/profiles/ProfileDeprecations.java
- src/test/java/com/rultor/agents/daemons/EndsDaemonITCase.java
#1100 is dealt with again here.
> #1100 illegal print from shell fixed

- CONTRIBUTING.md
- README.md
Related issue: https://github.com/yegor256/rultor/issues/1216
>  #1216 add CONTRIBUTING.md

- README.md
Related to issue https://github.com/yegor256/rultor/issues/1223
@yegor256 FYI
>  #1223 - tidy up what is rultor section

- .rultor.yml
+ add filfreire
+ remove darkled (user no longer exists on github)
related to issue #1226 
@yegor256 fyi
> #1226 - Update .rultor.yml merge commanders

- appveyor.yml
- shippable.yml
> #1317 Enables TLSv1.2 on Java 7 builds

- src/docker/Dockerfile
After this change, rultor will be able to merge the PR: https://github.com/yegor256/npm-files/pull/4
> upgrade: nodejs v6 -> nodejs v10

- .travis.yml
> #1313 Fixed Travis build

- appveyor.yml
> This should fix CI

- src/main/java/com/rultor/agents/req/StartsRequest.java
- src/main/java/com/rultor/profiles/GithubProfile.java
- src/main/java/com/rultor/spi/Profile.java
- src/test/java/com/rultor/agents/req/StartsRequestTest.java
1. Added `defaultBranch` method to `Profile`
2. `defaultBranch` is added for log message
3. Test added 
I'm not sure that it's correct to add method to the `Profile` interface, but I didn't found any other way to get a branch.
Closes: #1604
> feat(#1604) Add more informative message.

- pom.xml
- src/main/java/com/rultor/agents/github/qtn/QnMerge.java
- src/main/resources/phrases_en_US.properties
- src/test/java/com/rultor/agents/github/qtn/QnMergeTest.java
1. Make `QnMergeTest` work
2. Add one more disabled test for #1237 (Verify CI checks before merge)
> test(#1237): Resurrect `QnMergeTest`

- src/main/java/com/rultor/agents/github/qtn/QnMerge.java
- src/test/java/com/rultor/agents/AgentsTest.java
- src/test/java/com/rultor/agents/github/UnderstandsTest.java
- src/test/java/com/rultor/agents/github/qtn/QnMergeTest.java
Don't print redundant message if some checks were failed.
Closes: #1657
> feat(#1657): redundant message

- README.md
Minor edit in introducing Rultor. @rultor hello
> style(readme): bit typo first paragraph

- pom.xml
- src/main/java/com/rultor/Entry.java
- src/main/java/com/rultor/Routine.java
- src/main/java/com/rultor/agents/daemons/EndsDaemon.java
- src/main/java/com/rultor/agents/github/Answer.java
- src/main/java/com/rultor/agents/github/CommitsLog.java
- src/main/java/com/rultor/agents/github/StartsTalks.java
- src/main/java/com/rultor/agents/github/qtn/QnSince.java
- src/main/java/com/rultor/agents/github/qtn/QnStatus.java
- src/main/java/com/rultor/agents/twitter/Tweets.java
- src/main/java/com/rultor/cached/CdTalks.java
- src/main/java/com/rultor/dynamo/DyTalks.java
- src/main/java/com/rultor/profiles/Profiles.java
- src/main/java/com/rultor/web/TkDaemon.java
- src/main/java/com/rultor/web/TkHome.java
- src/main/java/com/rultor/web/TkSiblings.java
- src/main/java/com/rultor/web/TkSitemap.java
- src/main/java/com/rultor/web/TkStatus.java
- src/main/java/com/rultor/web/TkTicks.java
- src/test/java/com/rultor/agents/github/AnswerTest.java
- src/test/java/com/rultor/agents/github/CommitsLogTest.java
- src/test/java/com/rultor/agents/github/ReleaseBinariesTest.java
- src/test/java/com/rultor/web/TkHomeITCase.java
- src/test/java/com/rultor/web/TkTicksTest.java
includes #1873 
downgrade aspertjrt to 1.9.19 version
It is better to use one version aspertjrt with jcabi-aspects
> [#1871] downgrade aspectjrt

- src/main/java/com/rultor/agents/github/qtn/QnIfContains.java
- src/test/java/com/rultor/agents/github/qtn/QnIfContainsTest.java
Ignore commands inside `quoted text`
> [#1700] Ignore text commands inside ``

- pom.xml
- src/main/java/com/rultor/agents/Agents.java
- src/main/java/com/rultor/agents/aws/AwsEc2.java
- src/main/java/com/rultor/agents/aws/AwsEc2Image.java
- src/main/java/com/rultor/agents/aws/AwsEc2Instance.java
- src/main/java/com/rultor/agents/aws/StartsInstance.java
- src/main/java/com/rultor/agents/aws/StopsInstance.java
- src/main/java/com/rultor/agents/aws/package-info.java
- src/main/resources/META-INF/MANIFEST.MF
Running Ec2 instance from image
> [#1877] StopsInstanse and StartsInstance are created

- src/main/java/com/rultor/agents/daemons/Script.java
- src/main/java/com/rultor/agents/daemons/StartsDaemon.java
- src/main/java/com/rultor/agents/docker/DockerExec.java
- src/main/java/com/rultor/agents/docker/DockerHealthCheck.java
- src/main/java/com/rultor/agents/github/qtn/QnStatus.java
- src/main/java/com/rultor/agents/req/StartsRequest.java
- src/main/java/com/rultor/spi/Profile.java
- src/main/java/com/rultor/spi/Talk.java
- src/main/java/com/rultor/web/TkButton.java
- src/main/java/com/rultor/web/TkDaemon.java
- src/main/java/com/rultor/web/TkTicks.java
- src/test/java/com/rultor/agents/docker/DockerHealthCheckTest.java
- src/test/java/com/rultor/agents/req/DecryptTest.java
- src/test/java/com/rultor/agents/req/StartsRequestTest.java
- src/test/java/com/rultor/spi/TalkTest.java
- src/test/java/com/rultor/web/TkAppTest.java
- increased buffer for escaping answer
- log message for failed answer (with talk id)
- streams to resources are explicitly closed
> #1889 closing streams to resources

- README.md
- rultor_schema.json
- src/jekyll/_posts/2014/jul/2014-07-14-commands.md
Just a schema, it is not use to validate file during the work.
Fix #1307
> [#1307] json schema for .rultor.yml file

- src/main/java/com/rultor/agents/daemons/Script.java
- src/main/java/com/rultor/web/TkButton.java
- src/main/java/com/rultor/web/TkDaemon.java
There were a places, where param can have a null value. Delete this behaviour.
> Remove dangerous places
