yegor256/rultor

pom.xml
Changes for Issue #686
There are multiple errors that don't allow to build Rultor on Windows. I've added a check of OS family to the pom.xml with the message that explains it to not confuse developers.
=> Incomplete documentation: Prerequisites for running Rultor tests

src/main/java/com/rultor/agents/Mails.java, src/test/java/com/rultor/agents/MailsTest.java
#748 email notifications on release. Created MailsTest.
=> #748 email notifications on release

pom.xml, src/main/java/com/rultor/agents/twitter/Tweets.java, src/test/java/com/rultor/agents/twitter/TweetsTest.java
I had to add suppress for PMD, because it wasn't counting correctly the amount of `StringBuilder` reserved (PMD stated that builder was initialized with 16 capacity, while it is with 200)
=> #561 added languages tweets

src/main/java/com/rultor/agents/github/CommentsTag.java
The problem was that we still use `/git/` version of `Commit`, when I upgraded the jcabi-github (#671) I didn't notice that we were not using `RepoCommit` but `Commit`. So this commit is about coming back to the original implementation which works correctly with jcabi-github fix (jcabi/jcabi-github#943).
I've tested this using my github api key and retrieval of author login works correctly when using `RepoCommit`, bu gives null when using `Commit`.
It would be best to have a test for this, but that would require setting up a mock repository where we could create releases (and commit code, before each release) which seems like an overkill.
=> #726 using RepoCommit to get author login

src/test/java/com/rultor/agents/req/DecryptTest.java
This fixes the cause of https://github.com/yegor256/rultor/pull/859#issuecomment-107824659
An extra space in the XML was causing an extra space in the filename, thus causing gpg to attempt to open a nonexistent file whose name started with a space character.
=> DecryptTest.createTestProfileXML: rm spurious space that's breaking tests

src/main/resources/phrases_en_US.properties
This hints explicitly to the user that the yml file from the base branch
is taken which can be easily forgotten else.
Fixes https://github.com/yegor256/rultor/issues/873
=> resources: Improve `config` response

src/main/resources/com/rultor/agents/req/_head.sh
This removes the use of the ```--privileged```  flag from the script starting the Docker run.
The privileged flag creates a significant security issue for Rultor as it causes the host machine's devices to be fully accessible to the container run.
An attacker could take advantage of this fact and provide an image/script combination to Rultor that mounts the host's hard drive(s) (now available as a standard /dev/... ) into the container.  
Combined with the fact that the Docker daemon does run under the root user, an attacker can trivially gain full control of the host via a privileged container.
=> Removed --privileged Flag from Docker Container Run

README.md, pom.xml, src/docker/Dockerfile, src/docker/settings.xml
This resolves #946.
Versioneye shows 10 dependencies as outdated here: https://www.versioneye.com/user/projects/561a9d87a193340f28000fd3
* Updated those 10 in this PR.
* Updated Dockerfile to use Maven 3.3.3, since the newer plugins required more recent Maven than 3.2.1. 3.3.3 was the most recent I could make build on Ubuntu 14.04.
* Updated Readme accordingly, regarding the minimum Maven version.
=> #946 Updated outdated dependencies

src/main/resources/com/rultor/agents/req/_head.sh, src/test/java/com/rultor/agents/req/StartsRequestTest.java
#901 is solved by this.
* Make Docker container run using pseudo tty 
* Adjust unit-test slightly to account for added -t flag
This is hard to test in a 100% portable manner since it depends on the Docker host machine Rultor connects to via ssh, should work fine on any standard Linux system though. It's just that the Docker output is piped to a file that is then tailed on the host, given that this only involves stdOut from Docker we should be fine here though.
Difference is obvious :)
=> #901 make rultor run docker container in in tty mode

system.properties
#946 needs this, we forgot about this part.
See [here](https://devcenter.heroku.com/articles/java-support#specifying-a-maven-version) -> Heroku does not automatically upgrade Maven.
=> #946 Heroku does not automatically upgrade maven, we need to specify this manually

src/main/java/com/rultor/agents/daemons/Tail.java, src/test/java/com/rultor/agents/daemons/TailITCase.java
#884 is resolved by this:
* Added iconv filter on the tailing output
* Fixed the style breaking, no need to make this line longer :)
* Added unittest testing the correct conversion of  `"\u00ea"` to `"ê"`
=> #884 convert non-utf8 chars to utf8 when tailing Rultor output

src/main/java/com/rultor/agents/github/qtn/QnAskedBy.java, src/test/java/com/rultor/agents/github/qtn/QnAskedByTest.java, src/test/java/com/rultor/profiles/GithubProfileTest.java
#982 is fixed by this.
This is a very trivial correction of the first PR for this containing:
* corrected xpath to architects
* initial fix missed that those are a list :(, now fixed in test and production code
* also added test to yaml reading describing this fact.
=> #982, fixed xpath for xml representation of architects in yaml when answering questions

src/main/resources/com/rultor/agents/req/merge.sh
#935 is resolved by this.
Very straightforward fix in my opinion, this is essentially the same fix as the one reverted here https://github.com/yegor256/rultor/commit/e022a224f51f137e38090f4ea582bd952712e3c3.
The problem with that one was that if you have the same branch name in both remotes and checkout this way:
```bash
git checkout "origin/${head_branch}"
```
you're left in a detached head state. 
Added the `-B` flag that will automatically either create or hard reset the branch to the given remote to prevent this now and it should work fine.
=> #935 create a new branch from origin target branch,so that git does not fail the checkout because of ambiguous naming

.rultor.yml, Gemfile, pom.xml, src/docker/Dockerfile
#1037 is fixed by this.
* Locked in all Gemfile dependencies
* Locked in all related apt-get installed package dependencies
* Removed apt-get upgrade run from Dockerfile to make the above have any meaning
* Removed redundant bundle install from .rultor.yml install section given that this is also run from Maven (site target) anyhow.
* Also no need for showing the Jekyll version in the logs, we can read this from the bundler output anyhow.
=> #1037 fixed ruby depdendencies

years.sh
We missed this when we added the year check, the settings.xml is copied into this folder only when releasing, but it's breaking the release now that it's getting checked for copyright.
=> Exclude settings.xml from copyright check to fix release

src/main/java/com/rultor/agents/docker/DockerHealthCheck.java, src/main/resources/com/rultor/agents/docker/checkhost.sh, src/test/java/com/rultor/agents/docker/DockerHealthCheckTest.java, src/test/java/com/rultor/agents/docker/package-info.java
#1041 is resolved by this.
* Added script that needs to `exit 0` on a working Rultor SSH host.
* Added `SuperAgent` executing this script
* Added Test describing the `SuperAgent` behavior
* Added puzzle for integrating this with the existing SuperAgents
=> #1041 implemented docker daemon host health check

src/main/java/com/rultor/profiles/Profiles.java, src/test/java/com/rultor/profiles/ProfilesTest.java
#1039 I implemented validated method, that checks that merged .rultor.yml has no changes in architect and commander sections. I covered `validated` method by unit tests. I added one puzzle (to implement `merged` method, write IT for `validated` method and use it.
This is a copy of https://github.com/yegor256/rultor/pull/1064 that cannot be reopened. That's why I created new one.
=> #1039 Use merged and validated of version `.rultor.yml` for `merge` command.

src/main/java/com/rultor/profiles/ProfileDeprecations.java, src/test/java/com/rultor/agents/daemons/EndsDaemonITCase.java
#1100 is resolved here
* Catch broken profile exception when ending the talk and print exception message
* Added integration test to check this behaviour
=> #1100 print exceptions when reading profile to shell when ending job

pom.xml, src/main/java/com/rultor/Routine.java, src/main/java/com/rultor/agents/github/Reports.java
Quick fix for #1125 and puzzle asking for a lasting solution to this design issue.
The problem here is with `comment.body()` throwing an `AssertionException` since `RtJson` eventually runs this:
```java
public JsonObject fetch() throws IOException {
return this.request.fetch()
.as(RestResponse.class)
.assertStatus(HttpURLConnection.HTTP_OK)
.as(JsonResponse.class)
.json().readObject();
}
```
which gives us `AssertionException` if the initial deletion of the comment causes a `404` when Rultor tries to retrieve it.
In general these errors should not cause Rultor to globally die, but I don't have the time to handle this in a safe manner on short notice today. Hence I added the puzzle asking for a proper change in design here, preventing this and similar issues in the first place.
=> #1125 Preventing 

.travis.yml, src/docker/Dockerfile
This PR add building the docker image as part of Travis CI and two fixes which causes failure of building it.
`-q` or quiet flag is raised for docker build because it'll flood Travis build log and surpass the 4 MB limit, but if the docker build fail it'll display the logs if it fails.
=> Test the docker image

src/jekyll/_posts/2014/jul/2014-07-14-commands.md
Markdown couldn't tell where the end of the `code` syntax highlighting was. Adding a spaces isn't ideal but it's essentially harmless and fixes the issue.
=> fixed some markdown typos

src/docker/Dockerfile
The disclaimer is added so that users going for their own container may remove the package confidently.The disclaimer is added so that users going for their own container may remove the package confidently.
=> Disclaimer for the packages configured in Dockerfile

src/docker/Dockerfile
see https://twitter.com/nixcraft/status/1087769411941851137
images with oracle-jdk may be removed from docker hub
=> replaced oracle-jdk with open-jdk

src/main/java/com/rultor/profiles/GithubProfile.java
Since `jacabi-github` is already using `defaultBranch` instead of hardcoded "master" branch, we can remove that check.
=> Remove old workaround with master branch

src/main/resources/com/rultor/agents/req/release.sh, src/test/java/com/rultor/agents/req/StartsRequestTest.java
I've fixed the `release.sh` script - now it should work with any default branch (like `master` or `main`).
Closes: #1612.
=> feat(#1612): fix release script - now it can work with any branch

.github/workflows/mvn.yml
fix: use 3.8.7 maven version for mvn action
___
Update: It seems that it's impossible to specify `maven` version for `setup-java` action. You can read more about it [here](https://github.com/actions/setup-java/issues/457)
___
The actual problem with `minify` plugin that was broken after release a new maven version `3.9.0`. 
Exception log:
```java
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify (minify-js) on project rultor: Execution minify-js of goal com.samaxes.maven:minify-maven-plugin:1.7.6:minify failed: A required class was missing while executing com.samaxes.maven:minify-maven-plugin:1.7.6:minify: org/codehaus/plexus/util/DirectoryScanner
[ERROR] -----------------------------------------------------
[ERROR] realm = …
```
=> fix: use 3.8.7 maven version for mvn action

pom.xml, src/main/resources/com/rultor/web/daemon/head.html, src/main/resources/com/rultor/web/error.html.vm, src/main/xsl/layout.xsl, src/test/java/com/rultor/web/TkAppTest.java, src/test/java/com/rultor/web/TkHomeITCase.java
The proper solution for https://github.com/yegor256/rultor/pull/1627, that will work with new `maven 3.9.0` version.
1. Removed old `minify` plugin
2. Added new plugin `closure-compiler-maven-plugin` - the only branch from `minify` plugin. Here is the [link](https://github.com/blutorange/closure-compiler-maven-plugin).
3. The only problem - `closure-compiler-maven-plugin` works **ONLY** with `.js` files. By that reason we have to use `.css` files without _minification_ (but we can add an issue to solve that in the future).
=> Replace outdated `minify-maven-plugin` with `closure-compiler-maven-plugin` 

src/main/java/com/rultor/web/RsPage.java
Replace `RsFork` with `typedResponse` method. The current solution with typedResponse method is crutch, actually. The previous solution with `RsFork` was broken after the Maven `3.9.0` release. The proper solution would be to fix the original problem in [takes](https://github.com/yegor256/takes) framework and then to return the correct solution with `RsFork` back.
Original problem: https://github.com/yegor256/takes/issues/1207
Closes: #1633
=> feat(#1633): Replace `RsFork` with `typedResponse`

.github/workflows/mvn.yml
Since we solved all problems with the new Maven `3.9.0` version, we don't have to specify the particular maven version for GitHub actions.
=> Use latest maven version for GitHub actions

pom.xml, src/main/java/com/rultor/agents/github/qtn/QnMerge.java, src/test/java/com/rultor/agents/github/qtn/QnMergeTest.java
Added verification of check runs before merging pull requests.
Closes: #1237
=> feat(#1237): verify Pull Requests Check Runs before merging   

src/main/java/com/rultor/agents/github/qtn/QnSafe.java, src/test/java/com/rultor/agents/github/qtn/QnSafeTest.java
Print first line of the error message.
Closes: #1661
=> feat(#1661): print first line of a GitHub comment

src/main/java/com/rultor/agents/Agents.java, src/main/java/com/rultor/agents/github/CommentsTag.java, src/main/java/com/rultor/spi/Profile.java, src/test/java/com/rultor/agents/github/CommentsTagTest.java
Rultor used to ignore `release.pre:false` flag during a release. In this PR it was fixed.
Closes: #1758.
____
History:
- feat(#1758): add tests that show what we want to get
- feat(#1758): implement profile check before release
- feat(#1758): fix all the qulice suggestions
=> feat(#1758): fix bug with release.pre=false

.github/workflows/codecov.yml, src/main/java/com/rultor/agents/github/qtn/CheckablePull.java, src/main/java/com/rultor/agents/github/qtn/QnMerge.java, src/main/resources/phrases_en_US.properties, src/test/java/com/rultor/agents/github/qtn/QnMergeTest.java
- logic is added 
- test is disabled, as MkPull doesn't allow to work with files (too many code to write without it)
=> [#1459] do not merge in case .rultor file is in PR

src/main/java/com/rultor/agents/github/CommentsTag.java, src/test/java/com/rultor/agents/github/CommentsTagTest.java, src/test/java/com/rultor/agents/github/ReleaseBinariesTest.java
Get the value for release - pre from the comment if presented 
Fix #1701
=> [#1701] Get pre value from the comment (if presented)

src/jekyll/_posts/2014/jul/2014-07-07-index.md, src/main/java/com/rultor/agents/github/IssueUrl.java, src/main/java/com/rultor/agents/github/StartsTalks.java, src/test/java/com/rultor/agents/github/IssueUrlTest.java
issue id is parsed from url only from issue and pull request
Fix #1074 
Fix #1128
=> [#1074] Restrict answers from gitlab to issues and pr
